version: '2'
services:
  # mariaDB server
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - ./mysql/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=wallet
    ports:
      - "3306:3306"

  # webserver to interact with blockchain
  blockchain-sever:
    container_name: webserver
    build: ./webserver
    image: webserver
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - PEER_ADDRESS=vp0:7051
      - MEMBERSRVC_ADDRESS=membersrvc:7054
      - CCPATH=tno.nl/chaincode/agrifood
      - FRONTEND_ORIGIN=http://bctb1.sensorlab.tno.nl:3000
      - DEPLOY_WAITTIME=30
      - INVOKE_WAITTIME=10
      - DATABASE_HOST=mariadb
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=wallet
      - INIT_SQL_FILE=/mysql/scripts/init.sql
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
    volumes:
      # Chaincode volume
      - ./chaincode:/go/src/tno.nl/chaincode
      # Webserver volumes
      - ./webserver/app:/usr/app
      # - ./webserver/tmp/keyValStore:/tmp/keyValStore
      # DB query volumes
      - ./mysql/scripts:/mysql/scripts
    links:
      - mariadb
      - membersrvc
      - vp0
    command: sh -c "sleep 10; npm install --loglevel error && npm run grunt serve"

  # frontent-application to communicate with webserver
  frontend-client:
    container_name: frontend-client
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/frontend:/usr/app
    command: sh -c "npm install --loglevel error && npm start"

  # chaincode environment
  ccenvv_latest:
    container_name: ccenv_latest
    build: ./blockchain/ccenv
    image:  hyperledger/fabric-baseimage:latest

  # membership service
  membersrvc:
    image: hyperledger/fabric-membersrvc:x86_64-0.6.1-preview
    ports:
      - "7054:7054"
    environment:
      - MEMBERSRVC_CA_LOGGING_SERVER=INFO
      - MEMBERSRVC_CA_LOGGING_CA=INFO
      - MEMBERSRVC_CA_LOGGING_ECA=INFO
      - MEMBERSRVC_CA_LOGGING_ECAP=INFO
      - MEMBERSRVC_CA_LOGGING_ECAA=INFO
      - MEMBERSRVC_CA_LOGGING_ACA=INFO
      - MEMBERSRVC_CA_LOGGING_ACAP=INFO
      - MEMBERSRVC_CA_LOGGING_TCA=INFO
      - MEMBERSRVC_CA_LOGGING_TCAP=INFO
      - MEMBERSRVC_CA_LOGGING_TCAA=INFO
      - MEMBERSRVC_CA_LOGGING_TLSCA=INFO
    volumes:
      - ./blockchain/config/membersrvc.yaml:/opt/gopath/src/github.com/hyperledger/fabric/membersrvc/membersrvc.yaml
    command: membersrvc

  vp0:
    image: hyperledger/fabric-peer:x86_64-0.6.1-preview
    ports:
      - "7050:7050"
      - "7051:7051"
      - "7053:7053"
    environment:
      - CORE_PEER_ID=vp0
      - CORE_SECURITY_ENABLED=true
      - CORE_SECURITY_PRIVACY=true
      - CORE_SECURITY_ENROLLID=test_vp0
      - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
      - CORE_PEER_ADDRESSAUTODETECT=true
      # CORE_PEER_ADDRESS=bctb1.sensorlab.tno.nl:7051
      - CORE_PEER_DISCOVERY_PERIOD=60s
      - CORE_PEER_DISCOVERY_TOUCHPERIOD=61s
      # CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO:SMART_GOODS=DEBUG
      # CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
      # CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
      # CORE_PBFT_GENERAL_MODE=batch
      # CORE_PBFT_GENERAL_N=4
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
    links:
      - membersrvc
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./chaincode:/opt/gopath/src/tno.nl/chaincode
    command: sh -c "sleep 5; peer node start"